version: '3.8'

services:
  config-service:
    build: .
    ports:
      - "8010:8010"
    environment:
      - ENVIRONMENT=development
      - CONFIG_STORAGE_TYPE=file
      - CONFIG_BASE_PATH=/app/configs
      - BACKUP_PATH=/app/backups
      - CONSUL_HOST=consul
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./configs:/app/configs
      - ./backups:/app/backups
      - .:/app
    networks:
      - presencepro-network
    depends_on:
      - consul
      - redis

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -dev -client=0.0.0.0 -ui
    volumes:
      - consul_data:/consul/data
    networks:
      - presencepro-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Port différent pour éviter les conflits
    volumes:
      - redis_config_data:/data
    networks:
      - presencepro-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"  # Port différent pour éviter les conflits
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_config_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - presencepro-network

volumes:
  consul_data:
  redis_config_data:
  prometheus_config_data:

networks:
  presencepro-network:
    external: true
