version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: presencepro_auth_db
    environment:
      POSTGRES_DB: presencepro_auth
      POSTGRES_USER: presencepro
      POSTGRES_PASSWORD: presencepro123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - presencepro_network

  # Auth Service
  auth-service:
    build: .
    container_name: presencepro_auth_service
    environment:
      DATABASE_URL: postgresql://presencepro:presencepro123@postgres:5432/presencepro_auth
      SECRET_KEY: your-super-secret-key-change-this-in-production
      DEBUG: "False" # Set to False for production
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - presencepro_network
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  postgres_data:

networks:
  presencepro_network:
    driver: bridge
