global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'course-service'
    static_configs:
      - targets: ['course-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'face-recognition-service'
    static_configs:
      - targets: ['face-recognition-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'attendance-service'
    static_configs:
      - targets: ['attendance-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'justification-service'
    static_configs:
      - targets: ['justification-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8008']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'statistics-service'
    static_configs:
      - targets: ['statistics-service:8009']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
