version: '3.8'

services:
  course-service:
    build: .
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/presencepro_courses
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - SECRET_KEY=your-secret-key-change-in-production
      - CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000", "http://localhost:8001", "http://localhost:8002"]
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - presencepro-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=presencepro_courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - presencepro-network

volumes:
  postgres_data:

networks:
  presencepro-network:
    external: true
